#!/bin/bash

#module purge
#module load intel intelmpi fftw3 hdf5

# OCCIGEN
# module purge
module purge
module load intel/18.1 intelmpi/2018.1.163 hdf5/1.10.4
module load fftw/3.3.8
# module load intel/18.1 intelmpi/2018.1.163
# module load intel/19.4 intelmpi/2019.4.243
# module load intel/19.4 openmpi/intel/2.0.4
# module load gcc/8.3.0 openmpi/gnu/2.0.4

module list

# rm *.h5 *.e sendjob *.output *.log

# cp ../test_data/results.h5 .

# mv TDSEScheduler-*out oldlogs/
# mv logfile.log-* oldlogs/

which h5pcc 
export HDF5_USE_SHLIB=yes # default static lib fore h5pcc
h5pcc -c $TDSE_1D_SOURCE/constants.c $TDSE_1D_SOURCE/tools_algorithmic.c $TDSE_1D_SOURCE/tools_MPI-RMA.c $TDSE_1D_SOURCE/tools_hdf5.c $TDSE_1D_SOURCE/tridiag.c $TDSE_1D_SOURCE/tools_fftw3.c $TDSE_1D_SOURCE/tools.c $TDSE_1D_SOURCE/prop.c $TDSE_1D_SOURCE/singleTDSE.c $TDSE_1D_SOURCE/strided_scheduler_separated_outs_coarsen.c -L$HDF5_LIBDIR -lhdf5 -lhdf5_hl -lfftw3
h5pcc *.o -L$HDF5_LIBDIR -lhdf5 -lhdf5_hl -lm -lfftw3 -o test_strided3.e
rm *.o


echo 'compilation finished'
