#!/bin/bash

#module purge
#module load intel intelmpi hdf5

rm *.h5 *.e sendjob *.output

cp ../tx/results.h5 .
cp ../tx/results.h5 results2.h5
cp ../tx/sendjob .

# mpicc -O2 -lhdf5 -lhdf5_hl -c $HOME/git/1DTDSE/mpi_window_tuto.c
# mpicc *.o -lhdf5 -lhdf5_hl -lm -o pi_tuto.e
# rm *.o

#mpicc -O2 -lhdf5 -lhdf5_hl -c $HOME/git/1DTDSE/randomwrite.c
#mpicc *.o -lhdf5 -lhdf5_hl -lm -o rwrite.e
#rm *.o

#mpicc -O2 -lhdf5 -lhdf5_hl -c $HOME/git/1DTDSE/MPI-RMA_tools.c $HOME/git/1DTDSE/mpi_nxtval_tuto.c
#mpicc *.o -lhdf5 -lhdf5_hl -lm -o nxtval_tuto.e
#rm *.o

#mpicc -traceback -lhdf5 -lhdf5_hl -c $HOME/git/1DTDSE/MPI-RMA_tools.c $HOME/git/1DTDSE/mpi_nxtval_tuto.c
#mpicc *.o -traceback -lhdf5 -lhdf5_hl -lm -o nxtval_tuto.e
#rm *.o

#mpicc -traceback -lhdf5 -lhdf5_hl -c $HOME/git/1DTDSE/MPI-RMA_tools.c $HOME/git/1DTDSE/mpi_mutex_counter_tuto.c
#mpicc *.o -traceback -lhdf5 -lhdf5_hl -lm -o mutex_counter_tuto.e
#rm *.o

mpicc -traceback -lhdf5 -lhdf5_hl -c $HOME/git/1DTDSE/MPI-RMA_tools.c $HOME/git/1DTDSE/hdf5+mpi_tuto/rwhdf5_tuto.c
mpicc *.o -traceback -lhdf5 -lhdf5_hl -lm -o rwhdf5.e
rm *.o





#rm *.sh
#cp ../tx/rates_atomic.dat .
#cp ../tx/results.h5 .
#cp ../tx/argon.inp .
