#!/bin/bash
#SBATCH -J TEST-TDSE-HDF5-mutex
#SBATCH --nodes=1
#SBATCH --constraint=[HSW24|BDW28]
#SBATCH --ntasks=4
#SBATCH --ntasks-per-node=4
#SBATCH --time=00:25:00
#SBATCH --output hdf5.output

module purge
module load intel intelmpi hdf5

# srun --mpi=pmi2 -K1 -n $SLURM_NTASKS rwrite.e
# srun --mpi=pmi2 -K1 -n $SLURM_NTASKS mutex_counter_tuto.e
srun --mpi=pmi2 -K1 -n $SLURM_NTASKS rwhdf5.e


echo "terminated";
