#!/bin/bash

#module purge
#module load intel intelmpi hdf5

module purge
module load GCC/6.1.0 OpenMPI/1.10.2-GCC-6.1.0-psm-dbg HDF5/1.8.13-OpenMPI-1.10.2-GCC-6.1.0-psm FFTW/3.3.5-OpenMPI-1.10.2-GCC-6.1.0-psm-dbg

rm *.h5 *.e sendjob *.output *.log

cp ../tx/results.h5 .
cp ../tx/results.h5 results2.h5
cp ../tx/sendjob .

# mpicc -O2 -lhdf5 -lhdf5_hl -c $HOME/git/1DTDSE/mpi_window_tuto.c
# mpicc *.o -lhdf5 -lhdf5_hl -lm -o pi_tuto.e
# rm *.o

#mpicc -O2 -lhdf5 -lhdf5_hl -c $HOME/git/1DTDSE/randomwrite.c
#mpicc *.o -lhdf5 -lhdf5_hl -lm -o rwrite.e
#rm *.o

#mpicc -O2 -lhdf5 -lhdf5_hl -c $HOME/git/1DTDSE/MPI-RMA_tools.c $HOME/git/1DTDSE/mpi_nxtval_tuto.c
#mpicc *.o -lhdf5 -lhdf5_hl -lm -o nxtval_tuto.e
#rm *.o

#mpicc -traceback -lhdf5 -lhdf5_hl -c $HOME/git/1DTDSE/MPI-RMA_tools.c $HOME/git/1DTDSE/mpi_nxtval_tuto.c
#mpicc *.o -traceback -lhdf5 -lhdf5_hl -lm -o nxtval_tuto.e
#rm *.o

#mpicc -traceback -lhdf5 -lhdf5_hl -c $HOME/git/1DTDSE/MPI-RMA_tools.c $HOME/git/1DTDSE/mpi_mutex_counter_tuto.c
#mpicc *.o -traceback -lhdf5 -lhdf5_hl -lm -o mutex_counter_tuto.e
#rm *.o

#h5pcc  -c $HOME/git/1DTDSE/MPI-RMA_tools.c $HOME/git/1DTDSE/hdf5+mpi_tuto/rwhdf5_tuto.c -lhdf5 -lhdf5_hl
#h5pcc *.o -lhdf5 -lhdf5_hl -lm -o rwhdf5.e
#rm *.o

#h5pcc  -c $HOME/git/1DTDSE/MPI-RMA_tools.c $HOME/git/1DTDSE/hdf5_tools.c $HOME/git/1DTDSE/main.c -lhdf5 -lhdf5_hl
#h5pcc *.o -lhdf5 -lhdf5_hl -lm -o test.e
#rm *.o

h5pcc  -c $HOME/git/1DTDSE/MPI-RMA_tools.c $HOME/git/1DTDSE/hdf5_tools.c $HOME/git/1DTDSE/tridiag.c $HOME/git/1DTDSE/tools.c $HOME/git/1DTDSE/prop.c $HOME/git/1DTDSE/singleTDSE.c $HOME/git/1DTDSE/main.c -lhdf5 -lhdf5_hl -lfftw3
h5pcc *.o -lhdf5 -lhdf5_hl -lm -lfftw3 -o test2.e
rm *.o


echo 'compilation succesfull'


#rm *.sh
#cp ../tx/rates_atomic.dat .
#cp ../tx/results.h5 .
#cp ../tx/argon.inp .
