#!/bin/bash

SRC="../sources"
SRC_TEST="../benchmarks/interps"

# gfortran -c -g  -Wconversion -fimplicit-none -fbacktrace -ffree-line-length-0 -fcheck=all -ffpe-trap=invalid,zero,overflow,underflow -finit-real=nan ${SRC}/array_helper.f90 ${SRC}/test_bisection_search.f90 
/usr/bin/h5fc -c -g  -Wconversion -fimplicit-none -fbacktrace -ffree-line-length-0 -fcheck=all -ffpe-trap=invalid,zero,overflow,underflow -finit-real=nan ${SRC}/array_helper.f90 ${SRC}/hdf5_helper_serial.f90 ${SRC_TEST}/test_interps_interactive.f90 
/usr/bin/h5fc -o arrays_interactive.e -g -Wconversion -fimplicit-none -fbacktrace -ffree-line-length-0 -fcheck=all -ffpe-trap=invalid,zero,overflow,underflow -finit-real=nan *.o

# h5fc -c -g  -Wconversion -fimplicit-none -fbacktrace -ffree-line-length-0 -fcheck=all -ffpe-trap=invalid,zero,overflow,underflow -finit-real=nan ${SRC}/array_helper.f90 ${SRC}/hdf5_helper_serial.f90 ${SRC_TEST}/test_interps_interactive.f90 
# h5fc -o arrays_interactive.e -g -Wconversion -fimplicit-none -fbacktrace -ffree-line-length-0 -fcheck=all -ffpe-trap=invalid,zero,overflow,underflow -finit-real=nan *.o

rm *.o


# Wall -Wextra -Warray-temporaries -Wconversion -fimplicit-none -fbacktrace -ffree-line-length-0 -fcheck=all -ffpe-trap=invalid,zero,overflow,underflow -finit-real=nan