#!/bin/bash

SRC="../sources"

# gfortran -c -g  -Wconversion -fimplicit-none -fbacktrace -ffree-line-length-0 -fcheck=all -ffpe-trap=invalid,zero,overflow,underflow -finit-real=nan ${SRC}/array_helper.f90 ${SRC}/test_bisection_search.f90 
ifort -c -g   ${SRC}/array_helper.f90 ${SRC}/test_bisection_search3.f90 
ifort -o bisection.e -g *.o

rm *.o


# Wall -Wextra -Warray-temporaries -Wconversion -fimplicit-none -fbacktrace -ffree-line-length-0 -fcheck=all -ffpe-trap=invalid,zero,overflow,underflow -finit-real=nan