#!/bin/bash

# mkdir direct
# cp file2 direct

#module load Matlab

for fold in sim*; do 

	echo $fold

	cd figures_octave
	mkdir $fold
	cd ..
	

	
	cp $fold/figures/* figures_octave/$fold/

 

done

echo "done" 


