#!/bin/sh
rm *.o

ifort=/opt/intel/bin/ifort

# gcc -c ccode.c
$ifort -fopenmp -c writing_parallelized2.f90
$ifort -fopenmp -o loopss.out *.o
# export OMP_PROC_BIND=true
export OMP_NUM_THREADS=2
./loopss.out
# nohup ./loopss.out > exit_dft.txt &





