#!/bin/sh

#############################
# les directives PBS vont ici:

# Specify the working directory
#PBS -d .

# walltime (hh:mm::ss)
#PBS -l walltime=48:00:00

# Specify the number of nodes(nodes=) and the number of cores per nodes(ppn=) to be used
#PBS -l nodes=3:ppn=12:c6100

# fin des directives PBS
#############################

# modules cleaning
module purge
module add torque
module add intel-mpi torque-intel-mpi

# useful informations to print
echo "#############################" 
echo "User:" $USER
echo "Date:" `date`
echo "Host:" `hostname`
echo "Directory:" `pwd`
echo "PBS_JOBID:" $PBS_JOBID
echo "PBS_O_WORKDIR:" $PBS_O_WORKDIR
echo "PBS_NODEFILE: " `cat $PBS_NODEFILE | uniq`
echo "#############################" 

#############################

# Specify total number of processes = number of nodes x number of cores per node
NUMPROC=32

# Specify path to executable
myapp=~/CUPRAD2/binary/cuprad_avakas.e

I_MPI_FABRICS=shm:tmi mpirun -np $NUMPROC $myapp
