#!/bin/bash
#PBS -N CUPRAD_TDSE_base
#PBS -d
#PBS -l select=1:ncpus=16
#PBS -l walltime=03:00:00
#PBS -o MMA-CUPRAD-base.output
#PBS -j oe
#PBS -V

# Load your modules (adapt as needed for your system)
load_modules

# Echo commands to stdout
set -x

# ensure correct work dir
echo "Working directory: $(pwd)"

# Launch your application with MPI
mpirun -np 16 "$CUPRAD_HOME/build/cuprad.e"

#Diagnose the job
qstat -f -1 $PBS_JOBID