#!/bin/bash

#module purge
#module load intel intelmpi fftw3 hdf5

# ECLIPSE-ELI
module purge
module load GCC/6.1.0 OpenMPI/1.10.2-GCC-6.1.0-psm-dbg HDF5/1.8.13-OpenMPI-1.10.2-GCC-6.1.0-psm FFTW/3.3.5-OpenMPI-1.10.2-GCC-6.1.0-psm-dbg

# # OCCIGEN
# module purge
# module load intel/18.1 intelmpi/2018.1.163 hdf5/1.10.4
# module load fftw/3.3.8

# rm *.h5 *.e sendjob *.output *.log results/*

# cp ../tx/results_single.h5 results.h5
# cp ../tx/results_single.h5 results2.h5
which h5pcc 
# export HDF5_USE_SHLIB=yes # default static lib fore h5pcc
h5pcc  -c $TDSE_1D_HOME/constants.c $TDSE_1D_HOME/tools_hdf5.c $TDSE_1D_HOME/tridiag.c $TDSE_1D_HOME/tools.c $TDSE_1D_HOME/tools_fftw3.c $TDSE_1D_HOME/tools_algorithmic.c $TDSE_1D_HOME/prop.c $TDSE_1D_HOME/singleTDSE.c $TDSE_1D_HOME/single_caller.c -L$HDF5_LIBDIR -lhdf5 -lhdf5_hl -lfftw3 -g
h5pcc --echo  *.o -L$HDF5_LIBDIR -lhdf5 -lhdf5_hl -lm -lfftw3 -g -o test_s1.e
# rm *.o


echo 'compilation finished'


