#!/bin/bash

#PBS -N 5_1DTDSE_merge
#PBS -l select=1:ncpus=1:mem=4gb:scratch_local=2gb:cl_galdor=True
#PBS -l walltime=24:00:00
#PBS -o TDSE_prepare.output
#PBS -j oe
#PBS -V


module purge
load_python_modules

set -x

# echo "$PBS_JOBID is running on node `hostname -f` in a scratch directory $SCRATCHDIR" >> $SUBMITTING_DIRECTORY/jobs_info.txt


# python3 $TDSE_1D_PYTHON/merge.py -keep-files
python3 $TDSE_1D_PYTHON/merge.py