#!/bin/bash
#PBS -N MPI-TDSE
## #PBS -l walltime=48:00:00
#PBS -o MPI-TDSE.output
#PBS -j oe
#PBS -V



### Purge modules
module purge

load_modules

cd /scratch.shared/jvabek/BG_mono

mpirun socket $TDSE_1D_HOME/build/TDSE.e # numa

# possibilities to test different options for making MPI run more efficient https://www.open-mpi.org/doc/v3.0/man1/mpirun.1.php
# mpirun --bind-to socket $TDSE_1D_HOME/build/TDSE.e # numa